In [1]:
#Import required packages
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import numpy as np

In [2]:
tf.keras.__version__

'2.4.0'

In [3]:
# Getting the data ready
# Generate train dummy data for 1000 Students and dummy test for 500
#Columns :Age, Hours of Study & Avg Previous test scores
# np.random.seed(2018) #Setting seed for reproducibility
train_data, test_data = np.random.random((1000, 3)), np.random.random((500, 3))

In [4]:
train_data

array([[0.5389472 , 0.69860853, 0.12566626],
       [0.89071043, 0.23522969, 0.17744023],
       [0.35475698, 0.945018  , 0.00652532],
       ...,
       [0.43462742, 0.12245714, 0.6890848 ],
       [0.08754769, 0.7484373 , 0.95651671],
       [0.1448494 , 0.3566227 , 0.55788717]])

In [5]:
train_data.shape

(1000, 3)

In [6]:
#Generate dummy results for 1000 students : Whether Passed (1) or Failed (0)
labels = np.random.randint(2, size = (1000, 1))

In [7]:
labels

array([[1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
    

In [14]:
#Defining the model structure with the required layers,
# of neurons, activation function and optimizers
model = Sequential()

In [15]:
model.add(Dense(5, input_dim = 3, activation = 'relu'))

In [16]:
model.add(Dense(4, activation = 'relu'))

In [20]:
model.add(Dense(1, activation = 'sigmoid'))

In [21]:
model.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics = ['accuracy'])

In [22]:
#Train the model and make predictions
model.fit(train_data, labels, epochs=10, batch_size = 32)

Epoch 1/10
32/32 [==============================] - 0s 3ms/step - loss: 0.6945 - accuracy: 0.5000
Epoch 2/10
32/32 [==============================] - 0s 1ms/step - loss: 0.6940 - accuracy: 0.5000
Epoch 3/10
32/32 [==============================] - 0s 1ms/step - loss: 0.6938 - accuracy: 0.5000
Epoch 4/10
32/32 [==============================] - 0s 1ms/step - loss: 0.6936 - accuracy: 0.5000
Epoch 5/10
32/32 [==============================] - 0s 1000us/step - loss: 0.6935 - accuracy: 0.5000
Epoch 6/10
32/32 [==============================] - 0s 1ms/step - loss: 0.6934 - accuracy: 0.5000
Epoch 7/10
32/32 [==============================] - 0s 1ms/step - loss: 0.6933 - accuracy: 0.5000
Epoch 8/10
32/32 [==============================] - 0s 1ms/step - loss: 0.6933 - accuracy: 0.5000
Epoch 9/10
32/32 [==============================] - 0s 1ms/step - loss: 0.6932 - accuracy: 0.5000
Epoch 10/10
32/32 [==============================] - 0s 1ms/step - loss: 0.6932 - accuracy: 0.5000


In [23]:
#Make predictions from the trained model
predictions = model.predict(test_data)

In [24]:
predictions

array([[0.5037813 ],
       [0.5037813 ],
       [0.5037813 ],
       [0.5037813 ],
       [0.5037813 ],
       [0.5037813 ],
       [0.5037813 ],
       [0.5037813 ],
       [0.5037813 ],
       [0.5037813 ],
       [0.5037813 ],
       [0.5037813 ],
       [0.5037813 ],
       [0.5037813 ],
       [0.5037813 ],
       [0.5037813 ],
       [0.5037813 ],
       [0.5037813 ],
       [0.5037813 ],
       [0.5037813 ],
       [0.5037813 ],
       [0.5037813 ],
       [0.5037813 ],
       [0.5037813 ],
       [0.5037813 ],
       [0.5037813 ],
       [0.5037813 ],
       [0.5037813 ],
       [0.5037813 ],
       [0.5037813 ],
       [0.5037813 ],
       [0.5038304 ],
       [0.5037813 ],
       [0.5037813 ],
       [0.5037813 ],
       [0.5037813 ],
       [0.5037813 ],
       [0.5037813 ],
       [0.5037813 ],
       [0.5037813 ],
       [0.5037813 ],
       [0.5037813 ],
       [0.5037813 ],
       [0.5037813 ],
       [0.5037813 ],
       [0.5037813 ],
       [0.5037813 ],
       [0.503

In [25]:
predictions[0]

array([0.5037813], dtype=float32)