In [1]:
import tensorflow as tf
from tensorflow import keras

In [2]:
keras.__version__

'2.4.0'

# Activation Function

### Sigmoid Activation Function

#### keras.activations.sigmoid(x)

### ReLU Activation Function

#### keras.activations.relu(x,alpha=0.0, max_value=None, threshold=0)

### Leaky ReLU

#### keras.layers.LeakyReLU(x, alpha = 0.0, max_value = None)

# Model

#### model = keras.Sequential()

# Layers: Core Layers

### Dense Layer

In [3]:
# keras.layers.Dense(units, activation = None, use_bias = True,
#                   kernel_initializer = 'glorot_uniform',
#                   bias_initializer = 'zeros',
#                   kernel_regulizer = None,
#                   bias_regulizer = None,
#                   activity_regulizer = None,
#                   kernel_constraint = None,
#                   bias_constraint = None)

### Dropout Layer

In [4]:
# keras.layers.Dropout(rate, noise_shape = None, seed = None)

# Loss Funtions

### Mean Squared Error

In [5]:
# keras.losses.mean_squared_error(y_true, y_pred)

### Mean Absolute Error

In [6]:
# keras.losses.mean_absolute_error(y_true, y_pred)

### Mean Absolute Precentage Error

In [7]:
# keras.losses.mean_absolute_percentage_error(y_true, y_pred)

### Mean Squared Logarthmic Error

In [8]:
# keras.losses.mean_squared_logarithmic_error(y_true, y_pred)

## Popular Choices for Losses for Categorical Outcomes

### Binary Cross-entropy

In [9]:
# keras.losses.binary_crossentropy(y_true, y_pred, from_logits=False, label_smoothing=0)

### Categorical Cross-entropy

In [10]:
# keras.losses.categorical_crossentropy(y_true, y_pred, from_logits=False, label_smoothing=0)

# Optimizers

### Stochastic Gradient Descent (SGD)

In [11]:
# keras.optimizers.SGD(learning_rate=0.01, momentum=0.0, nesterov=False, decay = 0.0)

### Adam

In [12]:
# keras.optimizers.Adam(learning_rate=0.001, beta_1=0.9, beta_2=0.999, epsilon=1e-07,
#                          amsgrad=False, decay = 0.0)

### Adagrad

### Adadelta

### RMSProp

### Adamax

### Nadam

# Metrics

### Binary Accuracy

In [13]:
# keras.metrics.binary_accuracy(y_true, y_pred, threshold=0.5)

### Categorical Accuracy

In [14]:
# keras.metrics.categorical_accuracy(y_true, y_pred)

### Sparse Categorical Accuracy

In [15]:
# keras.metrics.sparse_categorical_accuracy(y_true, y_pred)

# Model Configuration

In [16]:
# model = keras.models.Sequential()

In [17]:
# model.add(keras.layers.Dense(32, input_dim = 10, activation = 'relu'))
# model.add(keras.layers.Dense(16, activation = 'relu'))
# model.add(keras.layers.Dense(1, activation = 'sigmoid'))

In [18]:
# model.compile(optimizer='Adam', loss='binary_crossentropy', metrics=['accuracy'])

# Model Training

In [19]:
import numpy as np

In [20]:
# Generate dummy training dataset
np.random.seed(2020)
x_train = np.random.random((6000, 10))
y_train = np.random.randint(2, size = (6000, 1))

In [21]:
x_train

array([[0.98627683, 0.87339195, 0.50974552, ..., 0.34331559, 0.86215894,
        0.15669967],
       [0.14088724, 0.75708028, 0.73632492, ..., 0.56142698, 0.12417878,
        0.31973648],
       [0.95321387, 0.13735679, 0.5694131 , ..., 0.45611937, 0.15585136,
        0.47604897],
       ...,
       [0.99629792, 0.3515813 , 0.91801664, ..., 0.67953284, 0.36953237,
        0.95323498],
       [0.43305994, 0.32229442, 0.04844357, ..., 0.47534698, 0.18244435,
        0.39612088],
       [0.74379997, 0.00623057, 0.27015102, ..., 0.39029908, 0.70436206,
        0.06763585]])

In [22]:
x_train.shape

(6000, 10)

In [23]:
y_train

array([[1],
       [1],
       [0],
       ...,
       [0],
       [0],
       [1]])

In [24]:
y_train.shape

(6000, 1)

In [25]:
# Generate dummmy validation dataset
x_val = np.random.random((2000, 10))
y_val = np.random.randint(2, size = (2000, 1))

In [26]:
# Generate dummy test dataset
x_test = np.random.random((2000, 10))
y_test = np.random.randint(2, size = (2000, 1))

In [27]:
# Define the model architecture
model = keras.models.Sequential()
model.add(keras.layers.Dense(64, input_dim = 10, activation = 'relu')) # Layer 1
model.add(keras.layers.Dense(32, activation = 'relu')) # Layer 2
model.add(keras.layers.Dense(16, activation = 'relu')) # Layer 3
model.add(keras.layers.Dense(8, activation = 'relu')) # Layer 4
model.add(keras.layers.Dense(4, activation = 'relu')) # Layer 5
model.add(keras.layers.Dense(1, activation = 'sigmoid')) # Output layer

In [28]:
# Configure the model
model.compile(optimizer='Adam', loss='binary_crossentropy', metrics=['accuracy'])

In [29]:
# Train the model
model.fit(x_train, y_train, batch_size=32, epochs=10, validation_data=(x_val, y_val))

Epoch 1/10
188/188 [==============================] - 1s 4ms/step - loss: 0.6935 - accuracy: 0.4972 - val_loss: 0.6933 - val_accuracy: 0.4885
Epoch 2/10
188/188 [==============================] - 0s 1ms/step - loss: 0.6932 - accuracy: 0.5038 - val_loss: 0.6933 - val_accuracy: 0.4820
Epoch 3/10
188/188 [==============================] - 0s 2ms/step - loss: 0.6932 - accuracy: 0.4967 - val_loss: 0.6935 - val_accuracy: 0.4790
Epoch 4/10
188/188 [==============================] - 0s 1ms/step - loss: 0.6931 - accuracy: 0.5045 - val_loss: 0.6933 - val_accuracy: 0.4880
Epoch 5/10
188/188 [==============================] - 0s 1ms/step - loss: 0.6931 - accuracy: 0.5030 - val_loss: 0.6936 - val_accuracy: 0.4780
Epoch 6/10
188/188 [==============================] - 0s 1ms/step - loss: 0.6933 - accuracy: 0.5122 - val_loss: 0.6937 - val_accuracy: 0.4790
Epoch 7/10
188/188 [==============================] - 0s 1ms/step - loss: 0.6931 - accuracy: 0.4998 - val_loss: 0.6936 - val_accuracy: 0.4805
Epoch 

# Model Evaluation

In [30]:
evaluate = model.evaluate(x_test, y_test)

63/63 [==============================] - 0s 746us/step - loss: 0.6934 - accuracy: 0.4950


In [31]:
print(evaluate)

[0.6933773756027222, 0.4950000047683716]


In [32]:
print(model.metrics_names)

['loss', 'accuracy']


In [33]:
# Make Prediction
pred = model.predict(x_test)

In [34]:
pred[:10]

array([[0.48917574],
       [0.5041588 ],
       [0.49547267],
       [0.49410182],
       [0.4962582 ],
       [0.48816985],
       [0.49864757],
       [0.4991756 ],
       [0.48773366],
       [0.50740653]], dtype=float32)

# Putting all building blocks of NN for real world dataset

## Boston House Prices Dataset

In [35]:
from tensorflow.keras.datasets import boston_housing

In [36]:
(x_train, y_train), (x_test, y_test) = boston_housing.load_data()

### Explore the data structure using basic python commands 

In [37]:
print("Type of the Dataset:",type(y_train))
print("Shape of training data :",x_train.shape)
print("Shape of training labels :",y_train.shape)
print("Shape of testing data :",type(x_test))
print("Shape of testing labels :",y_test.shape)

Type of the Dataset: <class 'numpy.ndarray'>
Shape of training data : (404, 13)
Shape of training labels : (404,)
Shape of testing data : <class 'numpy.ndarray'>
Shape of testing labels : (102,)


In [38]:
x_train[:3, :]

array([[1.23247e+00, 0.00000e+00, 8.14000e+00, 0.00000e+00, 5.38000e-01,
        6.14200e+00, 9.17000e+01, 3.97690e+00, 4.00000e+00, 3.07000e+02,
        2.10000e+01, 3.96900e+02, 1.87200e+01],
       [2.17700e-02, 8.25000e+01, 2.03000e+00, 0.00000e+00, 4.15000e-01,
        7.61000e+00, 1.57000e+01, 6.27000e+00, 2.00000e+00, 3.48000e+02,
        1.47000e+01, 3.95380e+02, 3.11000e+00],
       [4.89822e+00, 0.00000e+00, 1.81000e+01, 0.00000e+00, 6.31000e-01,
        4.97000e+00, 1.00000e+02, 1.33250e+00, 2.40000e+01, 6.66000e+02,
        2.02000e+01, 3.75520e+02, 3.26000e+00]])

In [39]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation

### Extract the last 100 rows from the training data to create the validation datasets

In [40]:
x_val = x_train[300:,]
y_val = y_train[300:,]

### Define model structure

In [41]:
model = Sequential()

In [42]:
model.add(Dense(13, input_dim = 13, kernel_initializer = 'normal', activation = 'relu'))
model.add(Dense(6, kernel_initializer = 'normal', activation = 'relu'))
model.add(Dense(1, kernel_initializer = 'normal'))

### Compile model

In [43]:
model.compile(loss='mean_squared_error', optimizer = 'adam',
              metrics=['mean_absolute_percentage_error'])

### Train model

In [44]:
model.fit(x_train, y_train, batch_size=32, epochs=3, validation_data=(x_val, y_val))

Epoch 1/3
13/13 [==============================] - 0s 12ms/step - loss: 566.7032 - mean_absolute_percentage_error: 97.6604 - val_loss: 646.5753 - val_mean_absolute_percentage_error: 96.3623
Epoch 2/3
13/13 [==============================] - 0s 2ms/step - loss: 539.6003 - mean_absolute_percentage_error: 94.2275 - val_loss: 607.9684 - val_mean_absolute_percentage_error: 92.1068
Epoch 3/3
13/13 [==============================] - 0s 3ms/step - loss: 495.0490 - mean_absolute_percentage_error: 88.0881 - val_loss: 544.9922 - val_mean_absolute_percentage_error: 84.7128


### Evaluate

In [45]:
results = model.evaluate(x_test, y_test)

4/4 [==============================] - 0s 1ms/step - loss: 486.3073 - mean_absolute_percentage_error: 82.6500


In [46]:
for i in range(len(model.metrics_names)):
    print(model.metrics_names[i], ": ", results[i])

loss :  486.3072814941406
mean_absolute_percentage_error :  82.64997863769531


### Train the model again for better accuracy

In [47]:
model.fit(x_train, y_train, batch_size=32, epochs=30, validation_data=(x_val, y_val))

Epoch 1/30
13/13 [==============================] - 0s 7ms/step - loss: 425.0675 - mean_absolute_percentage_error: 77.9481 - val_loss: 451.0977 - val_mean_absolute_percentage_error: 72.5550
Epoch 2/30
13/13 [==============================] - 0s 3ms/step - loss: 330.4767 - mean_absolute_percentage_error: 63.2807 - val_loss: 334.5087 - val_mean_absolute_percentage_error: 55.7591
Epoch 3/30
13/13 [==============================] - 0s 3ms/step - loss: 228.0413 - mean_absolute_percentage_error: 48.4685 - val_loss: 224.3272 - val_mean_absolute_percentage_error: 42.0998
Epoch 4/30
13/13 [==============================] - 0s 3ms/step - loss: 153.3775 - mean_absolute_percentage_error: 42.0472 - val_loss: 157.2805 - val_mean_absolute_percentage_error: 37.6525
Epoch 5/30
13/13 [==============================] - 0s 3ms/step - loss: 124.2876 - mean_absolute_percentage_error: 42.9486 - val_loss: 138.8385 - val_mean_absolute_percentage_error: 39.5123
Epoch 6/30
13/13 [==============================] 

### Evaluate again

In [48]:
results = model.evaluate(x_test, y_test)

4/4 [==============================] - 0s 1ms/step - loss: 74.5473 - mean_absolute_percentage_error: 35.0155


In [49]:
for i in range(len(model.metrics_names)):
    print(model.metrics_names[i], ": ", results[i])

loss :  74.54732513427734
mean_absolute_percentage_error :  35.01551818847656


In [50]:
model.fit(x_train, y_train, batch_size=32, epochs=10, validation_data=(x_val, y_val))

Epoch 1/10
13/13 [==============================] - 0s 7ms/step - loss: 68.3735 - mean_absolute_percentage_error: 31.5809 - val_loss: 85.7755 - val_mean_absolute_percentage_error: 26.7049
Epoch 2/10
13/13 [==============================] - 0s 4ms/step - loss: 67.8068 - mean_absolute_percentage_error: 30.9299 - val_loss: 85.9535 - val_mean_absolute_percentage_error: 26.4906
Epoch 3/10
13/13 [==============================] - 0s 4ms/step - loss: 68.3475 - mean_absolute_percentage_error: 29.9747 - val_loss: 86.4332 - val_mean_absolute_percentage_error: 26.1964
Epoch 4/10
13/13 [==============================] - 0s 3ms/step - loss: 68.1897 - mean_absolute_percentage_error: 32.2226 - val_loss: 84.5781 - val_mean_absolute_percentage_error: 27.1728
Epoch 5/10
13/13 [==============================] - 0s 3ms/step - loss: 67.2694 - mean_absolute_percentage_error: 30.7793 - val_loss: 86.1796 - val_mean_absolute_percentage_error: 26.0859
Epoch 6/10
13/13 [==============================] - 0s 3ms/s

In [51]:
results = model.evaluate(x_test, y_test)

4/4 [==============================] - 0s 1ms/step - loss: 72.7389 - mean_absolute_percentage_error: 34.7699


In [52]:
for i in range(len(model.metrics_names)):
    print(model.metrics_names[i], ": ", results[i])

loss :  72.73885345458984
mean_absolute_percentage_error :  34.76986312866211
