# Exercises

#### 1. Prove that the transpose of a matrix  A ’s transpose is  A :  (A<sup>T</sup>)<sup>⊤</sup>=A .

In [1]:
import tensorflow as tf

In [2]:
A = tf.reshape(tf.range(20), (5, 4))
A

<tf.Tensor: shape=(5, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])>

In [3]:
A_transpose = tf.transpose(A)
A_transpose

<tf.Tensor: shape=(4, 5), dtype=int32, numpy=
array([[ 0,  4,  8, 12, 16],
       [ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19]])>

In [4]:
A_transpose_transpose = tf.transpose(A_transpose)
A_transpose_transpose

<tf.Tensor: shape=(5, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])>

In [5]:
A == A_transpose_transpose

<tf.Tensor: shape=(5, 4), dtype=bool, numpy=
array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])>

#### 2. Given two matrices  A  and  B , show that the sum of transposes is equal to the transpose of a sum:  
#### A<sup>T</sup>+B<sup>T</sup>=(A+B)<sup>T</sup> .

In [6]:
A_transpose

<tf.Tensor: shape=(4, 5), dtype=int32, numpy=
array([[ 0,  4,  8, 12, 16],
       [ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19]])>

In [7]:
B = A
B_transpose = tf.transpose(B)
B_transpose

<tf.Tensor: shape=(4, 5), dtype=int32, numpy=
array([[ 0,  4,  8, 12, 16],
       [ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19]])>

In [8]:
A_plus_B = A + B
A_plus_B

<tf.Tensor: shape=(5, 4), dtype=int32, numpy=
array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30],
       [32, 34, 36, 38]])>

In [9]:
(A_transpose + B_transpose) == tf.transpose(A_plus_B)

<tf.Tensor: shape=(4, 5), dtype=bool, numpy=
array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])>

#### 3. Given any square matrix  A , is  A+A<sup>T</sup>  always symmetric? Why?

In [10]:
A = tf.reshape(tf.range(25), (5, 5))
A_transpose = tf.transpose(A)
A, A_transpose

(<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
 array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]])>,
 <tf.Tensor: shape=(5, 5), dtype=int32, numpy=
 array([[ 0,  5, 10, 15, 20],
        [ 1,  6, 11, 16, 21],
        [ 2,  7, 12, 17, 22],
        [ 3,  8, 13, 18, 23],
        [ 4,  9, 14, 19, 24]])>)

In [11]:
A + A_transpose

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[ 0,  6, 12, 18, 24],
       [ 6, 12, 18, 24, 30],
       [12, 18, 24, 30, 36],
       [18, 24, 30, 36, 42],
       [24, 30, 36, 42, 48]])>

#### 4. We defined the tensor X of shape (2, 3, 4) in this section. What is the output of len(X)?

In [12]:
X = tf.random.normal((2, 3, 4))
X

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[ 0.6751777 ,  2.9189887 ,  0.01172035, -2.0966883 ],
        [-1.6759607 ,  0.16457438,  0.11786126, -0.27469653],
        [-0.19182472, -1.9693424 , -0.30630267,  1.7814155 ]],

       [[-0.15874852, -0.11303237, -0.15712163, -1.0995107 ],
        [-0.422797  ,  0.5360303 , -1.1231041 , -1.0368038 ],
        [ 2.3858721 ,  1.096249  ,  0.7796057 ,  0.4046856 ]]],
      dtype=float32)>

In [13]:
len(X)

2

In [14]:
x = tf.range(5)
len(x)

5

In [15]:
A

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])>

In [16]:
len(A)

5

In [17]:
A = tf.reshape(tf.range(24), (2, 3, 4))
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])>

In [18]:
tf.reduce_sum(A, axis=0)

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])>

In [19]:
tf.reduce_sum(A, axis=1)

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[12, 15, 18, 21],
       [48, 51, 54, 57]])>

In [20]:
tf.reduce_sum(A, axis=2)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 6, 22, 38],
       [54, 70, 86]])>

In [21]:
C = tf.reshape(tf.range(36), (3, 3, 4))
C

<tf.Tensor: shape=(3, 3, 4), dtype=int32, numpy=
array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]]])>

In [22]:
tf.reduce_sum(C, axis=0)

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[36, 39, 42, 45],
       [48, 51, 54, 57],
       [60, 63, 66, 69]])>

In [23]:
tf.reduce_sum(C, axis=1)

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[12, 15, 18, 21],
       [48, 51, 54, 57],
       [84, 87, 90, 93]])>

In [24]:
tf.reduce_sum(C, axis=2)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[  6,  22,  38],
       [ 54,  70,  86],
       [102, 118, 134]])>

#### 9. Feed a tensor with 3 or more axes to the linalg.norm function and observe its output. What does this function compute for tensors of arbitrary shape?

In [31]:
# vector
x = tf.constant([3, 4], dtype=tf.float32)
x, tf.linalg.norm(x)

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([3., 4.], dtype=float32)>,
 <tf.Tensor: shape=(), dtype=float32, numpy=5.0>)

In [33]:
# matrix
Y = tf.reshape(tf.range(4, dtype=tf.float32), (2, 2))
Y, tf.linalg.norm(Y)

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[0., 1.],
        [2., 3.]], dtype=float32)>,
 <tf.Tensor: shape=(), dtype=float32, numpy=3.7416575>)

In [34]:
# tensor with order 3
Z = tf.reshape(tf.range(12, dtype=tf.float32), (2, 2, 3))
Z, tf.linalg.norm(Z)

(<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
 array([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],
 
        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]], dtype=float32)>,
 <tf.Tensor: shape=(), dtype=float32, numpy=22.494444>)