# Linear Algebra

### Scalars

In [2]:
# a scalar is represented by a tensor with just one element
import tensorflow as tf

x = tf.constant(3.4)
y = tf.constant(4.0)

# some basic mathematical operations
x + y, x - y, x * y, x / y, x ** y

(<tf.Tensor: shape=(), dtype=float32, numpy=7.4>,
 <tf.Tensor: shape=(), dtype=float32, numpy=-0.5999999>,
 <tf.Tensor: shape=(), dtype=float32, numpy=13.6>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.85>,
 <tf.Tensor: shape=(), dtype=float32, numpy=133.63362>)

### Vecotrs

In [3]:
# think of a vector as simply a list of scalar values
x = tf.range(5)
x

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 1, 2, 3, 4])>

In [4]:
# access any element by indexing into tensor
x[2]

<tf.Tensor: shape=(), dtype=int32, numpy=2>

### Length, Dimensionality and Shape

In [5]:
# length gives dimension of the vector
len(x)

5

In [6]:
# shape
x.shape

TensorShape([5])

### Matrices

In [7]:
# creates mxn matrix
X = tf.reshape(tf.range(30), (5, 6))
X

<tf.Tensor: shape=(5, 6), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])>

In [8]:
# transpose of matrix
Y = tf.transpose(X)
Y

<tf.Tensor: shape=(6, 5), dtype=int32, numpy=
array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])>

In [9]:
# check symmetricity
X == Y

<tf.Tensor: shape=(), dtype=bool, numpy=False>

In [10]:
# symmetric matrix
B = tf.constant([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
B

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [2, 0, 4],
       [3, 4, 5]])>

In [11]:
B == tf.transpose(B)

<tf.Tensor: shape=(3, 3), dtype=bool, numpy=
array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])>

### Tensors

In [12]:
# generic way of describing n-dimensional arrays with an arbitrary number os axes
X = tf.reshape(tf.range(24), (2, 3, 4))
X

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])>

In [13]:
tf.reshape(X, (2, 2, 2, 3))

<tf.Tensor: shape=(2, 2, 2, 3), dtype=int32, numpy=
array([[[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]],


       [[[12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23]]]])>

### Basic Properties of Tensor Arithmetic

In [14]:
# addition
A = tf.reshape(tf.range(20, dtype=tf.float32), (5, 4))
B = A
A, A + B

(<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
 array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]], dtype=float32)>,
 <tf.Tensor: shape=(5, 4), dtype=float32, numpy=
 array([[ 0.,  2.,  4.,  6.],
        [ 8., 10., 12., 14.],
        [16., 18., 20., 22.],
        [24., 26., 28., 30.],
        [32., 34., 36., 38.]], dtype=float32)>)

In [15]:
# Hadamard Product: elementwise multiplication of two matrices
A * B

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[  0.,   1.,   4.,   9.],
       [ 16.,  25.,  36.,  49.],
       [ 64.,  81., 100., 121.],
       [144., 169., 196., 225.],
       [256., 289., 324., 361.]], dtype=float32)>

In [16]:
# multiplying or adding tensor by a scalar
a = 3
X = tf.reshape(tf.range(24), (2, 3, 4))
a + X, a * X, (a * X).shape

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 3,  4,  5,  6],
         [ 7,  8,  9, 10],
         [11, 12, 13, 14]],
 
        [[15, 16, 17, 18],
         [19, 20, 21, 22],
         [23, 24, 25, 26]]])>,
 <tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 0,  3,  6,  9],
         [12, 15, 18, 21],
         [24, 27, 30, 33]],
 
        [[36, 39, 42, 45],
         [48, 51, 54, 57],
         [60, 63, 66, 69]]])>,
 TensorShape([2, 3, 4]))

### Reduction

In [17]:
# sum of their elements
x = tf.range(5, dtype=tf.float32)
x, tf.reduce_sum(x)

(<tf.Tensor: shape=(5,), dtype=float32, numpy=array([0., 1., 2., 3., 4.], dtype=float32)>,
 <tf.Tensor: shape=(), dtype=float32, numpy=10.0>)

In [18]:
# sum of matrix of shape mxn
A, A.shape, tf.reduce_sum(A)

(<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
 array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]], dtype=float32)>,
 TensorShape([5, 4]),
 <tf.Tensor: shape=(), dtype=float32, numpy=190.0>)

In [19]:
# specify the axis alog which the tensor is reduced via summation
tf.reduce_sum(A, axis=0) # column-wise addition

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([40., 45., 50., 55.], dtype=float32)>

In [20]:
tf.reduce_sum(A, axis=1) # row-wise addition

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([ 6., 22., 38., 54., 70.], dtype=float32)>

In [21]:
tf.reduce_sum(A, axis=[0, 1])

<tf.Tensor: shape=(), dtype=float32, numpy=190.0>

In [27]:
# mean calculation
tf.reduce_mean(A), tf.reduce_sum(A) / tf.size(A).numpy()

(<tf.Tensor: shape=(), dtype=float32, numpy=9.5>,
 <tf.Tensor: shape=(), dtype=float32, numpy=9.5>)

In [28]:
# calculating mean along the specified axis
tf.reduce_mean(A, axis=0), tf.reduce_sum(A, axis=0) / A.shape[0]

(<tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 8.,  9., 10., 11.], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 8.,  9., 10., 11.], dtype=float32)>)

In [30]:
tf.reduce_mean(A, axis=1), tf.reduce_sum(A, axis=1) / A.shape[1]

(<tf.Tensor: shape=(5,), dtype=float32, numpy=array([ 1.5,  5.5,  9.5, 13.5, 17.5], dtype=float32)>,
 <tf.Tensor: shape=(5,), dtype=float32, numpy=array([ 1.5,  5.5,  9.5, 13.5, 17.5], dtype=float32)>)

### Non-Reduction Sum

In [32]:
sum_A = tf.reduce_sum(A, axis=1, keepdims=True)
sum_A

<tf.Tensor: shape=(5, 1), dtype=float32, numpy=
array([[ 6.],
       [22.],
       [38.],
       [54.],
       [70.]], dtype=float32)>

In [33]:
A

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.],
       [16., 17., 18., 19.]], dtype=float32)>

In [34]:
A / sum_A

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[0.        , 0.16666667, 0.33333334, 0.5       ],
       [0.18181819, 0.22727273, 0.27272728, 0.3181818 ],
       [0.21052632, 0.23684211, 0.2631579 , 0.28947368],
       [0.22222222, 0.24074075, 0.25925925, 0.2777778 ],
       [0.22857143, 0.24285714, 0.25714287, 0.27142859]], dtype=float32)>

In [36]:
A + sum_A

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[ 6.,  7.,  8.,  9.],
       [26., 27., 28., 29.],
       [46., 47., 48., 49.],
       [66., 67., 68., 69.],
       [86., 87., 88., 89.]], dtype=float32)>

In [38]:
# cumulative sum along specified axis
tf.cumsum(A, axis=0)

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.],
       [ 4.,  6.,  8., 10.],
       [12., 15., 18., 21.],
       [24., 28., 32., 36.],
       [40., 45., 50., 55.]], dtype=float32)>

In [39]:
tf.cumsum(A, axis=1)

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[ 0.,  1.,  3.,  6.],
       [ 4.,  9., 15., 22.],
       [ 8., 17., 27., 38.],
       [12., 25., 39., 54.],
       [16., 33., 51., 70.]], dtype=float32)>

### Dot Product

In [42]:
# sum over product of element at the same position
x = tf.range(4, dtype=tf.float32)
y = tf.ones(4, dtype=tf.float32)
x, y, tf.tensordot(x, y, axes=1)

(<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0., 1., 2., 3.], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([1., 1., 1., 1.], dtype=float32)>,
 <tf.Tensor: shape=(), dtype=float32, numpy=6.0>)

In [43]:
tf.reduce_sum(x * y)

<tf.Tensor: shape=(), dtype=float32, numpy=6.0>

### Matrix-Vector Product

In [44]:
A.shape, x.shape, tf.linalg.matvec(A, x)

(TensorShape([5, 4]),
 TensorShape([4]),
 <tf.Tensor: shape=(5,), dtype=float32, numpy=array([ 14.,  38.,  62.,  86., 110.], dtype=float32)>)

In [46]:
A, x

(<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
 array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([0., 1., 2., 3.], dtype=float32)>)

### Matrix-Matrix Multiplication

In [47]:
B = tf.ones((4, 3), tf.float32)
A, B, tf.matmul(A, B)

(<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
 array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]], dtype=float32)>,
 <tf.Tensor: shape=(4, 3), dtype=float32, numpy=
 array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=float32)>,
 <tf.Tensor: shape=(5, 3), dtype=float32, numpy=
 array([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]], dtype=float32)>)

### Norms
#### how big the vector is ie. not dimensionality but the magnitude
#### Euclidean distance is a norm ie. L2 norm

In [49]:
# L2 norm
u = tf.constant([3.0, -4.0])
tf.norm(u)

<tf.Tensor: shape=(), dtype=float32, numpy=5.0>

In [50]:
# L1 norm
tf.reduce_sum(tf.abs(u))

<tf.Tensor: shape=(), dtype=float32, numpy=7.0>

In [54]:
# Frobenius norm of a matrix: satisfies the properties of the vector norm
A, tf.norm(A)

(<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
 array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]], dtype=float32)>,
 <tf.Tensor: shape=(), dtype=float32, numpy=49.699093>)

# Exercises