# Documentation

### Finding All the Functions and Classes in a Module

In [1]:
import tensorflow as tf 
dir(tf.random)

['Algorithm',
 'Generator',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_sys',
 'all_candidate_sampler',
 'categorical',
 'create_rng_state',
 'experimental',
 'fixed_unigram_candidate_sampler',
 'gamma',
 'get_global_generator',
 'learned_unigram_candidate_sampler',
 'log_uniform_candidate_sampler',
 'normal',
 'poisson',
 'set_global_generator',
 'set_seed',
 'shuffle',
 'stateless_binomial',
 'stateless_categorical',
 'stateless_gamma',
 'stateless_normal',
 'stateless_parameterized_truncated_normal',
 'stateless_poisson',
 'stateless_truncated_normal',
 'stateless_uniform',
 'truncated_normal',
 'uniform',
 'uniform_candidate_sampler']

### Finding the Usage of Specific Functions and Classes

In [2]:
help(tf.ones)

Help on function ones in module tensorflow.python.ops.array_ops:

ones(shape, dtype=tf.float32, name=None)
    Creates a tensor with all elements set to one (1).
    
    See also `tf.ones_like`, `tf.zeros`, `tf.fill`, `tf.eye`.
    
    This operation returns a tensor of type `dtype` with shape `shape` and
    all elements set to one.
    
    >>> tf.ones([3, 4], tf.int32)
    <tf.Tensor: shape=(3, 4), dtype=int32, numpy=
    array([[1, 1, 1, 1],
           [1, 1, 1, 1],
           [1, 1, 1, 1]], dtype=int32)>
    
    Args:
      shape: A `list` of integers, a `tuple` of integers, or
        a 1-D `Tensor` of type `int32`.
      dtype: Optional DType of an element in the resulting `Tensor`. Default is
        `tf.float32`.
      name: Optional string. A name for the operation.
    
    Returns:
      A `Tensor` with all elements set to one (1).



In [3]:
tf.ones((4, 4))

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [4]:
list?

Init signature: list(iterable=(), /)
Docstring:     
Built-in mutable sequence.

If no argument is given, the constructor creates a new empty list.
The argument must be an iterable if specified.
Type:           type
Subclasses:     _HashedSeq, StackSummary, DeferredConfigList, SList, _ImmutableLineList, FormattedText, NodeList, _ExplodedList, Stack, _Accumulator, ...


In [5]:
list??

Init signature: list(iterable=(), /)
Docstring:     
Built-in mutable sequence.

If no argument is given, the constructor creates a new empty list.
The argument must be an iterable if specified.
Type:           type
Subclasses:     _HashedSeq, StackSummary, DeferredConfigList, SList, _ImmutableLineList, FormattedText, NodeList, _ExplodedList, Stack, _Accumulator, ...


In [6]:
dir(tf.linalg)

['LinearOperator',
 'LinearOperatorAdjoint',
 'LinearOperatorBlockDiag',
 'LinearOperatorBlockLowerTriangular',
 'LinearOperatorCirculant',
 'LinearOperatorCirculant2D',
 'LinearOperatorCirculant3D',
 'LinearOperatorComposition',
 'LinearOperatorDiag',
 'LinearOperatorFullMatrix',
 'LinearOperatorHouseholder',
 'LinearOperatorIdentity',
 'LinearOperatorInversion',
 'LinearOperatorKronecker',
 'LinearOperatorLowRankUpdate',
 'LinearOperatorLowerTriangular',
 'LinearOperatorPermutation',
 'LinearOperatorScaledIdentity',
 'LinearOperatorToeplitz',
 'LinearOperatorTridiag',
 'LinearOperatorZeros',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_sys',
 'adjoint',
 'band_part',
 'banded_triangular_solve',
 'cholesky',
 'cholesky_solve',
 'cross',
 'det',
 'diag',
 'diag_part',
 'eig',
 'eigh',
 'eigvals',
 'eigvalsh',
 'einsum',
 'experimental',
 'expm',
 'eye',
 'global_norm',
 'inv',
 'l2_normalize',
 'logdet

In [7]:
help(tf.linalg)

Help on package tensorflow._api.v2.linalg in tensorflow._api.v2:

NAME
    tensorflow._api.v2.linalg - Operations for linear algebra.

PACKAGE CONTENTS
    experimental (package)

FILE
    /usr/local/lib/python3.8/dist-packages/tensorflow/_api/v2/linalg/__init__.py




In [8]:
tf.norm?

Signature: tf.norm(tensor, ord='euclidean', axis=None, keepdims=None, name=None)
Docstring:
Computes the norm of vectors, matrices, and tensors.

This function can compute several different vector norms (the 1-norm, the
Euclidean or 2-norm, the inf-norm, and in general the p-norm for p > 0) and
matrix norms (Frobenius, 1-norm, 2-norm and inf-norm).

Args:
  tensor: `Tensor` of types `float32`, `float64`, `complex64`, `complex128`
  ord: Order of the norm. Supported values are `'fro'`, `'euclidean'`,
    `1`, `2`, `np.inf` and any positive real number yielding the corresponding
    p-norm. Default is `'euclidean'` which is equivalent to Frobenius norm if
    `tensor` is a matrix and equivalent to 2-norm for vectors.
    Some restrictions apply:
      a) The Frobenius norm `'fro'` is not defined for vectors,
      b) If axis is a 2-tuple (matrix norm), only `'euclidean'`, '`fro'`, `1`,
         `2`, `np.inf` are supported.
    See the description of `axis` on how to compute norms for a b