# Getting Started

In [1]:
import tensorflow as tf

In [2]:
x = tf.range(12)
x

<tf.Tensor: shape=(12,), dtype=int32, numpy=array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])>

In [3]:
x.shape

TensorShape([12])

In [4]:
tf.size(x)

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [5]:
X = tf.reshape(x, (3, 4))

In [6]:
X

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])>

In [7]:
tf.size(X)

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [8]:
X.shape

TensorShape([3, 4])

In [9]:
tf.zeros((2, 3, 4))

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)>

In [10]:
tf.ones((2, 3, 4))

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)>

In [11]:
tf.random.normal((3, 4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 0.63460493,  2.1259942 ,  0.24508204, -0.11455701],
       [-1.3731922 ,  0.35780224, -0.5615313 , -1.0638412 ],
       [ 0.02341858,  0.02607303,  0.06963608,  0.16998453]],
      dtype=float32)>

In [12]:
tf.constant([[1, 2, 3, 4], [4, 1, 2, 3], [3, 4, 1, 2], [2, 3, 4, 1]])

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[1, 2, 3, 4],
       [4, 1, 2, 3],
       [3, 4, 1, 2],
       [2, 3, 4, 1]])>

# Operations

In [13]:
# common standard arithmetic operations
x = tf.constant([1.0, 2, 4, 8])
y = tf.constant([2.0, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y

(<tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 3.,  4.,  6., 10.], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([-1.,  0.,  2.,  6.], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 2.,  4.,  8., 16.], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([0.5, 1. , 2. , 4. ], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 1.,  4., 16., 64.], dtype=float32)>)

In [14]:
tf.exp(x), tf.exp(y)

(<tf.Tensor: shape=(4,), dtype=float32, numpy=
 array([2.7182817e+00, 7.3890562e+00, 5.4598148e+01, 2.9809580e+03],
       dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([7.389056, 7.389056, 7.389056, 7.389056], dtype=float32)>)

In [15]:
# concatenate multiple tensors
X = tf.reshape(tf.range(12, dtype=tf.float32), (3, 4))
Y = tf.constant([[2.0, 1, 4, 3], [1, 2, 3, 4], [3, 4, 1, 2]])
tf.concat([X, Y], axis=0), tf.concat([X, Y], axis=1)

(<tf.Tensor: shape=(6, 4), dtype=float32, numpy=
 array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 3.,  4.,  1.,  2.]], dtype=float32)>,
 <tf.Tensor: shape=(3, 8), dtype=float32, numpy=
 array([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  3.,  4.,  1.,  2.]], dtype=float32)>)

In [16]:
X, Y, X == Y

(<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
 array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]], dtype=float32)>,
 <tf.Tensor: shape=(3, 4), dtype=float32, numpy=
 array([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [3., 4., 1., 2.]], dtype=float32)>,
 <tf.Tensor: shape=(3, 4), dtype=bool, numpy=
 array([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])>)

In [17]:
# summing all elements in the tensor
tf.reduce_sum(X)

<tf.Tensor: shape=(), dtype=float32, numpy=66.0>

In [18]:
tf.reduce_all(X == Y)

<tf.Tensor: shape=(), dtype=bool, numpy=False>

# Broadcasting Mechanism

In [19]:
# even when shapes differ, we can still perform elementwise operations by 
# invoking the broadcasting mechanism. 
a = tf.reshape(tf.range(3), (3, 1))
b = tf.reshape(tf.range(2), (1, 2))
a, b

(<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
 array([[0],
        [1],
        [2]])>,
 <tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[0, 1]])>)

In [20]:
a + b

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[0, 1],
       [1, 2],
       [2, 3]])>

# Indexing and Slicing

In [21]:
X

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]], dtype=float32)>

In [22]:
X[-1]

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 8.,  9., 10., 11.], dtype=float32)>

In [23]:
X[1:3]

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]], dtype=float32)>

In [24]:
X[1:3, 1:4]

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 5.,  6.,  7.],
       [ 9., 10., 11.]], dtype=float32)>

In [26]:
# Variables in Tensorflow: Mutable containers of state in Tensorflow
X_var = tf.Variable(X)
X_var

<tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]], dtype=float32)>

In [29]:
# Variable assignment
X_var[1, 2].assign(0)
# X_var[2, 2] = 99 # does not support item assignment
X_var

<tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  0.,  7.],
       [ 8.,  9., 10., 11.]], dtype=float32)>

In [30]:
X_var = tf.Variable(X)
X_var[0:2, 0:3].assign(tf.ones(X_var[0:2, 0:3].shape, dtype=tf.float32))
X_var

<tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[ 1.,  1.,  1.,  3.],
       [ 1.,  1.,  1.,  7.],
       [ 8.,  9., 10., 11.]], dtype=float32)>

In [31]:
X_var[0:2, 0:3].assign(tf.ones(X_var[0:2, 0:3].shape, dtype=tf.float32) * 10)
X_var

<tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[10., 10., 10.,  3.],
       [10., 10., 10.,  7.],
       [ 8.,  9., 10., 11.]], dtype=float32)>

In [32]:
Y_var = tf.Variable(Y)
Y_var

<tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[2., 1., 4., 3.],
       [1., 2., 3., 4.],
       [3., 4., 1., 2.]], dtype=float32)>

In [33]:
Y_var = tf.Variable(Y[0:2, :])
Y_var

<tf.Variable 'Variable:0' shape=(2, 4) dtype=float32, numpy=
array([[2., 1., 4., 3.],
       [1., 2., 3., 4.]], dtype=float32)>

In [34]:
X_var1 = tf.Variable(X)
X_var1

<tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]], dtype=float32)>

# Saving Memory

In [35]:
before = id(Y)
before

2273599689296

In [36]:
Y = X + Y

In [37]:
id(Y)

2273633755200

In [38]:
Y += X

In [39]:
id(Y)

2273633758720

In [40]:
id(Y) == before

False

In [41]:
Y

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 2.,  3.,  8.,  9.],
       [ 9., 12., 15., 18.],
       [19., 22., 21., 24.]], dtype=float32)>

In [ ]:
A = X + Y